(MAS-2) Pydantify project
antony3595/comments_aio pull request #2
Opened 2024-07-12 16:24 UTC by antony3595

Подключить библиотеку Pydantic для валидации данных

Внутри приложения использовать только объекты Pydantic, не передавать туда сюда dict данные и не работать с ними напрямую

При получении постов и комментариев они сразу должны быть провалидированы и превращены в Pydantic объекты

Компонент обновления комментариев также должен валидировать входящие данные с помощью Pydantic

Теперь вместе с ID он также должен принимать email 

Добавить дополнительные правила валидации для ID, чтобы обязательно были случаи ошибок. Например:

ID не может быть равен 25 и 55 - будем считать что это зарезервированные ID

ID не может быть 3-значным числом, у которого все знаки одинаковые.

Ошибка валидации должны логироваться, но не прерывать работу приложения

2024-07-16 20:15 UTC, MasterAlish requested changes

2024-07-16 20:15 UTC, MasterAlish commented on app_types/json_placeholder.py
> +    userId: Optional[PositiveInt] = Field(default=None)
После введения Union типа, когда можно несколько возможных типов указывать, например так `int | float`, также рекомендуют использовать  `PositiveInt | None` вместо Optional[PositiveInt]`

2024-07-16 20:15 UTC, MasterAlish commented on app_types/json_placeholder.py
> +from typing import Optional
Переименуй `app_types` либо в `schema` либо в `data_models`. Так более правильно называть модели данных

2024-07-16 20:15 UTC, MasterAlish commented on app_types/tcp_server.py
> +        if len(str(v)) == 3 and len(set(str(v))) == 1:
Можно отделить две валидации в два разных валидатора?

2024-07-16 20:15 UTC, MasterAlish commented on clients/tcp_client.py
> +    async def update_comment(self, comment: Comment):
Укажи во всех методах типы параметров и возвращаемого значения как в предыдущем файле.

2024-07-16 20:15 UTC, MasterAlish commented on Dockerfile
> +CMD ["echo", "Specify the command to run at the docker-compose.yml file"]
Этого разве не было в предыдущем PR?

2024-07-25 19:27 UTC, antony3595 commented on Dockerfile
> +CMD ["echo", "Specify the command to run at the docker-compose.yml file"]
Эта ветка была создана из MAS-1, но PR на слияние в master, поэтому сначала нужно смерджить mas-1, потом эту

2024-07-27 05:16 UTC, MasterAlish approved these changes

2024-07-28 04:15 UTC, merged