Mas 6
antony3595/comments_aio pull request #6
Opened 2024-09-26 17:36 UTC by antony3595

Добавить возможность подписаться на новости.

Добавить enum для указания категорий новостей с 10 разными вариантами.

В Модель новостей добавить возможность указать категории. Одна новость может быть сразу в нескольких категориях. 

Добавить API endpoint POST /news/subscribe где пользовать подписаться на категории новостей. 

Scope news 

В параметрах можно указать список категорий, в т.ч. пустой.

Список категорий пользователя обновляется полностью. Старые удаляются

Добавить API endpoint GET /news/subscriptions который возвращает список новостей, на которые пользователь подписан.

Возвращаются новости только тех категорий, на которые пользователь подписан

Последние новости возвращаются первыми в списке

Должна быть пагинация. По умолчанию 10 страниц на запрос.

2024-10-22 02:50 UTC, MasterAlish requested changes

2024-10-22 02:50 UTC, MasterAlish commented on alembic/versions/4bda85823d17_news_categories.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Часто приходится потом читать миграции. А иногда вручную редактировать. Поэтому желательно тут тоже иметь порядок в коде. Например: убирать вот эти комменты. Добавлять отступы в код, чтобы было легче читать.

2024-10-22 02:50 UTC, MasterAlish commented on api/dependencies/auth.py
> +    def __init__(self, api_key: str = Depends(APIKeyHeader(name="X-API-KEY", scheme_name="X-API-KEY"))):
Почему поменял здесь?

2024-10-22 02:50 UTC, MasterAlish commented on services/auth/authorizaton.py
> -        if not UserRepository().read(db, query=UserEmailQuery(email=token_payload.email)):
Получается раньше здесь не работало? ) async метод вызывался без await

2024-10-22 02:50 UTC, MasterAlish commented on schema/query/user.py
> +    id: int | None = Field(None, alias="id")
Не совсем понял где это используется и почему объявлен по другому.

2024-10-22 02:50 UTC, MasterAlish commented on repository/user.py
> +        stmt = await db.execute(select(UserCategorySubscription).where(UserCategorySubscription.user_id == user_id))
когда вызываешь execute() возвращается уже не statement , а result. Т.е. запрос в БД выполняется. Поэтому нужно переименовать.

2024-10-22 02:50 UTC, MasterAlish commented on repository/news.py
> +        result = [NewsSchema.model_validate(news_item, from_attributes=True) for news_item in news]
Наверное тебе тоже не понравилось в цикле сериализовывать список моделей? ) А в DRF можно одним методом ) Может поищешь способ тут тоже сделать также? Вроде есть какой-то TypeAdapter

2024-11-12 16:35 UTC, antony3595 commented on alembic/versions/4bda85823d17_news_categories.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Согласен. И я специально оставляю комменты, если миграция была сделана автоматически. А если ручная, то удаляю их )))
Чтобы потом было очевидно, это алембик сгенерил, или кто-то говна понаписал.

2024-11-12 16:39 UTC, antony3595 commented on api/dependencies/auth.py
> +    def __init__(self, api_key: str = Depends(APIKeyHeader(name="X-API-KEY", scheme_name="X-API-KEY"))):
В Swagger`e запарился в один Authorization вставлять то jwt то ключ. Поэтому header для авторизации по API ключу назвал по другому

2024-11-21 17:57 UTC, antony3595 commented on schema/query/user.py
> +    id: int | None = Field(None, alias="id")
Это модель для экземпляра для чтения пользователя из БД, раньше читал только по email, теперь добавился id. Одно из этих полей обязательное, вот и валидирую наличие одного

2024-11-26 15:17 UTC, merged